export const mockRankingData = [
  {
    rank: 1,
    user_id: "u004",
    user_name: "赵雨萱",
    total_minutes: 320,
    current_streak: 23,
    total_hours: "5h 20m",
  },
  {
    rank: 2,
    user_id: "u008",
    user_name: "吴梦琪",
    total_minutes: 280,
    current_streak: 18,
    total_hours: "4h 40m",
  },
  {
    rank: 3,
    user_id: "u002",
    user_name: "李思雨",
    total_minutes: 240,
    current_streak: 8,
    total_hours: "4h 00m",
  },
  {
    rank: 4,
    user_id: "u012",
    user_name: "林思彤",
    total_minutes: 220,
    current_streak: 7,
    total_hours: "3h 40m",
  },
  {
    rank: 5,
    user_id: "u006",
    user_name: "刘诗涵",
    total_minutes: 210,
    current_streak: 15,
    total_hours: "3h 30m",
  },
  {
    rank: 6,
    user_id: "u010",
    user_name: "孙雅婷",
    total_minutes: 195,
    current_streak: 11,
    total_hours: "3h 15m",
  },
  {
    rank: 7,
    user_id: "u001",
    user_name: "张小明",
    total_minutes: 185,
    current_streak: 12,
    total_hours: "3h 05m",
  },
  {
    rank: 8,
    user_id: "u007",
    user_name: "周子轩",
    total_minutes: 175,
    current_streak: 9,
    total_hours: "2h 55m",
  },
  {
    rank: 9,
    user_id: "u011",
    user_name: "黄嘉伟",
    total_minutes: 160,
    current_streak: 4,
    total_hours: "2h 40m",
  },
  {
    rank: 10,
    user_id: "u003",
    user_name: "王浩然",
    total_minutes: 150,
    current_streak: 5,
    total_hours: "2h 30m",
  },
];

export const fallbackRankingData = mockRankingData;
